[package]
name = "rectangle"
version = "0.1.0"
edition = "2024"

[dependencies]
# bytemuck = { version = "1.22.*", features = ["extern_crate_alloc"] }
eframe = "0.31.1"
egui = "0.31.1"
image = "0.24.*"
itertools = "0.14.0"
rand = "0.9.1"
# ref-cast = "1.0.24"
